basePath: /
host: https://ws-ats-714220050-cc57ecdf5b73.herokuapp.com
info:
  contact:
    email: 714220050@std.ulbi.ac.id
    name: API Support
    url: https://github.com/mhrndiva
  description: This is a sample swagger for Fiber
  title: TES SWAGGER ULBI
  version: "1.0"
paths: {}
schemes:
- https
- http
swagger: "2.0"
